from setuptools import find_packages, setup

setup(
    name="piano-key-detector",
    version="0.2.0",
    description="Detect the first white key from top-down keyboard images",
    author="AutoGenerated",
    packages=find_packages(),
    install_requires=[
        "opencv-python",
        "numpy",
        "pillow",
        "streamlit",
    ],
    python_requires=">=3.8",
    include_package_data=True,
)
